spring:
  application:
    name: validation-example

  datasource:
    url: jdbc:postgresql://localhost:5432/demopost
    username: postgres
    password: Passw0rd@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  logging:
    level:
      org.springframework.web: DEBUG


server:
    port: 9280
